[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyxn"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "prek>=0.3.3",
    "pytest>=9.0.2",
    "pytest-cases>=3.9.1",
    "ruff>=0.15.3",
    "ty>=0.0.18",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",      # pydocstyle
    "PLR",    # pylint-refactor
    "PTH",    # don't force pathlib
    "COM812", # conflict with format
    "T201",   # print is fine
    "ERA001", # commented-out code is fine
    "ISC001", # conflict with formatter
    "EM102",  # too pedantic
    "TRY003", # too pedantic
    "C901",   # too pedantic
    "BLE001", # too pedantic
    "RUF023", # too pedantic
]

[tool.ruff.lint.flake8-annotations]
suppress-none-returning = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"test_*.py" = ["INP001", "S101"]
